"""crear tabla horarios_clase

Revision ID: 12d7140a7ba1
Revises: 34919a6d6e0b
Create Date: 2026-08-04 14:22:33.794445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d7140a7ba1'
down_revision: Union[str, Sequence[str], None] = '34919a6d6e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_academicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_clase_id'), 'horarios_clase', ['id'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    op.execute("""
        ALTER TABLE horarios_clase
        ADD CONSTRAINT no_choque_aula
        EXCLUDE USING gist (
            aula_id WITH =,
            periodo_id WITH =,
            dia_semana WITH =,
            tsrange(
                ('2000-01-01'::timestamp + hora_inicio),
                ('2000-01-01'::timestamp + hora_fin)
            ) WITH &&
        ) WHERE (activo = true);
    """)
    op.execute("""
        ALTER TABLE horarios_clase
        ADD CONSTRAINT no_choque_docente
        EXCLUDE USING gist (
            docente_id WITH =,
            periodo_id WITH =,
            dia_semana WITH =,
            tsrange(
                ('2000-01-01'::timestamp + hora_inicio),
                ('2000-01-01'::timestamp + hora_fin)
            ) WITH &&
        ) WHERE (activo = true);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horarios_clase_id'), table_name='horarios_clase')
    op.execute("ALTER TABLE horarios_clase DROP CONSTRAINT IF EXISTS no_choque_docente;")
    op.execute("ALTER TABLE horarios_clase DROP CONSTRAINT IF EXISTS no_choque_aula;")
    op.drop_table('horarios_clase')
    # ### end Alembic commands ###
