"""agregar logo_url a configuracion_institucion

Revision ID: 413a7c657c45
Revises: 5dbffd4114f8
Create Date: 2026-08-11 22:15:11.088729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413a7c657c45'
down_revision: Union[str, Sequence[str], None] = '5dbffd4114f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion_institucion', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_institucion', 'logo_url')
    # ### end Alembic commands ###
