"""crear tablas academico: periodos programas materias grupos

Revision ID: 4279688bb134
Revises: 3fec914b722f
Create Date: 2026-08-03 21:39:06.140537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4279688bb134'
down_revision: Union[str, Sequence[str], None] = '3fec914b722f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_periodos_academicos_id'), 'periodos_academicos', ['id'], unique=False)
    op.create_table('programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_programas_id'), 'programas', ['id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_academicos.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_programas_id'), table_name='programas')
    op.drop_table('programas')
    op.drop_index(op.f('ix_periodos_academicos_id'), table_name='periodos_academicos')
    op.drop_table('periodos_academicos')
    # ### end Alembic commands ###
