"""crear tabla configuracion_institucion

Revision ID: 5dbffd4114f8
Revises: f10f5cb05a20
Create Date: 2026-08-10 12:56:41.612753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbffd4114f8'
down_revision: Union[str, Sequence[str], None] = 'f10f5cb05a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_institucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('dias_operacion', sa.String(length=100), nullable=False),
    sa.Column('duracion_sesion_minutos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_institucion_id'), 'configuracion_institucion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_institucion_id'), table_name='configuracion_institucion')
    op.drop_table('configuracion_institucion')
    # ### end Alembic commands ###
