"""crear tabla excepciones_horario

Revision ID: cff61ffab464
Revises: 12d7140a7ba1
Create Date: 2026-08-04 15:38:19.108893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff61ffab464'
down_revision: Union[str, Sequence[str], None] = '12d7140a7ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excepciones_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_clase_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['horario_clase_id'], ['horarios_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excepciones_horario_id'), 'excepciones_horario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excepciones_horario_id'), table_name='excepciones_horario')
    op.drop_table('excepciones_horario')
    # ### end Alembic commands ###
