"""crear tabla solicitudes_cambio

Revision ID: d37ada652349
Revises: cff61ffab464
Create Date: 2026-08-04 15:50:15.227970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37ada652349'
down_revision: Union[str, Sequence[str], None] = 'cff61ffab464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_cambio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_clase_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_afectada', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('respuesta_coordinador', sa.Text(), nullable=True),
    sa.Column('excepcion_generada_id', sa.Integer(), nullable=True),
    sa.Column('coordinador_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resuelto_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coordinador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['excepcion_generada_id'], ['excepciones_horario.id'], ),
    sa.ForeignKeyConstraint(['horario_clase_id'], ['horarios_clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_cambio_id'), 'solicitudes_cambio', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_cambio_id'), table_name='solicitudes_cambio')
    op.drop_table('solicitudes_cambio')
    # ### end Alembic commands ###
